from decimal import Decimal


class TaxRules2026:
    EMPLOYEE_INPS_RATE = Decimal("0.0919")
    ADDITIONAL_INPS_RATE = Decimal("0.01")
    ADDITIONAL_INPS_THRESHOLD = Decimal("56224")

    IRPEF_FIRST_THRESHOLD = Decimal("28000")
    IRPEF_SECOND_THRESHOLD = Decimal("50000")

    IRPEF_FIRST_RATE = Decimal("0.23")
    IRPEF_SECOND_RATE = Decimal("0.33")
    IRPEF_THIRD_RATE = Decimal("0.43")

    EMPLOYEE_DEDUCTION_FIRST_THRESHOLD = Decimal("15000")
    EMPLOYEE_DEDUCTION_SECOND_THRESHOLD = Decimal("28000")
    EMPLOYEE_DEDUCTION_THIRD_THRESHOLD = Decimal("50000")

    EMPLOYEE_DEDUCTION_FIRST_AMOUNT = Decimal("1955")

    EMPLOYEE_DEDUCTION_SECOND_BASE = Decimal("1910")
    EMPLOYEE_DEDUCTION_SECOND_VARIABLE = Decimal("1190")
    EMPLOYEE_DEDUCTION_SECOND_DENOMINATOR = Decimal("13000")

    EMPLOYEE_DEDUCTION_THIRD_BASE = Decimal("1910")
    EMPLOYEE_DEDUCTION_THIRD_DENOMINATOR = Decimal("22000")

    EMPLOYEE_DEDUCTION_BONUS_LOWER_BOUND = Decimal("25000")
    EMPLOYEE_DEDUCTION_BONUS_UPPER_BOUND = Decimal("35000")
    EMPLOYEE_DEDUCTION_BONUS_AMOUNT = Decimal("65")

    LOMBARDY_FIRST_THRESHOLD = Decimal("15000")
    LOMBARDY_SECOND_THRESHOLD = Decimal("28000")
    LOMBARDY_THIRD_THRESHOLD = Decimal("50000")

    LOMBARDY_FIRST_RATE = Decimal("0.0123")
    LOMBARDY_SECOND_RATE = Decimal("0.0158")
    LOMBARDY_THIRD_RATE = Decimal("0.0172")
    LOMBARDY_FOURTH_RATE = Decimal("0.0173")

    MILAN_EXEMPTION_THRESHOLD = Decimal("23000")
    MILAN_RATE = Decimal("0.008")

    